import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css";
import NavigationBar from "../_components/navbar/navBar";
import { auth } from "@/auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const sesh = await auth();
  console.log(sesh);
  const name = sesh?.user.name!.split(" ")!;

  return (
    <html lang="en">
      <body className={inter.className + " flex"}>
        <NavigationBar name={`${name[0]} ${name.pop()![0]}.`} />
        {children}
      </body>
    </html>
  );
}
